from allennlp.models.encoder_decoders.simple_seq2seq import SimpleSeq2Seq
from allennlp.models.encoder_decoders.simple_seq2seq_crf import SimpleSeq2SeqCrf
from allennlp.models.encoder_decoders.simple_seq2multiseq import SimpleSeq2MultiSeq
from allennlp.models.encoder_decoders.simple_seqtask2seq import SimpleSeqTask2Seq
